# Generated by Django 4.1.2 on 2022-10-07 12:52

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название поставщика')),
                ('country', django_countries.fields.CountryField(max_length=2, verbose_name='Страна')),
                ('year_foundation', models.PositiveIntegerField(blank=True, verbose_name='Год основания')),
                ('balance', models.IntegerField(default=0, verbose_name='Баланс поставщика, USD')),
                ('amount_of_clients', models.PositiveIntegerField(blank=True, verbose_name='Количество покупателей-автосалонов')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Поставщик',
                'verbose_name_plural': 'Поставщики',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DiscountProducer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя скидки')),
                ('amount_discount', models.PositiveIntegerField(verbose_name='Размер скидки в %')),
                ('quantity_cars_max', models.PositiveIntegerField(blank=True, null=True, verbose_name='Max количество авто для применения скидки')),
                ('quantity_cars_min', models.PositiveIntegerField(blank=True, null=True, verbose_name='Min количество авто для применения скидки')),
                ('description', models.TextField(blank=True, max_length=500)),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('producers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producer.producer', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Скидка поставщика',
                'verbose_name_plural': 'Скидки поставщика',
            },
        ),
        migrations.CreateModel(
            name='ActionProducer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя акции')),
                ('amount_action', models.PositiveIntegerField(verbose_name='Размер скидки по акции в %')),
                ('date_start', models.DateTimeField(verbose_name='Дата начала акции (dd.mm.yyyy 00:00:00)')),
                ('date_finish', models.DateTimeField(verbose_name='Дата окончания акции (dd.mm.yyyy 00:00:00)')),
                ('description', models.TextField(blank=True, max_length=500)),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('producers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producer.producer', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Акция поставщика',
                'verbose_name_plural': 'Акции поставщика',
            },
        ),
    ]
