# Generated by Django 4.1.2 on 2022-10-10 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producer',
            name='amount_of_clients',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество покупателей-автосалонов'),
        ),
    ]
