# Generated by Django 4.1.2 on 2022-10-10 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producer', '0002_alter_producer_amount_of_clients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producer',
            name='year_foundation',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Год основания'),
        ),
    ]
