# Generated by Django 4.1.2 on 2022-10-10 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producer', '0003_alter_producer_year_foundation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discountproducer',
            options={'verbose_name': 'Скидка постоянного клиента поставщика', 'verbose_name_plural': 'Скидки постоянного клиента поставщика'},
        ),
        migrations.AlterField(
            model_name='actionproducer',
            name='amount_action',
            field=models.PositiveIntegerField(verbose_name='Скидка в %'),
        ),
        migrations.AlterField(
            model_name='actionproducer',
            name='date_finish',
            field=models.DateTimeField(verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='actionproducer',
            name='date_start',
            field=models.DateTimeField(verbose_name='Дата начала'),
        ),
        migrations.AlterField(
            model_name='actionproducer',
            name='description',
            field=models.TextField(blank=True, max_length=500, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='actionproducer',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='discountproducer',
            name='description',
            field=models.TextField(blank=True, max_length=500, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='discountproducer',
            name='quantity_cars_max',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Max количество приобретенных авто для скидки'),
        ),
        migrations.AlterField(
            model_name='discountproducer',
            name='quantity_cars_min',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Min количество приобретенных авто для скидки'),
        ),
        migrations.AlterField(
            model_name='producer',
            name='balance',
            field=models.IntegerField(default=0, verbose_name='Баланс, USD'),
        ),
        migrations.AlterField(
            model_name='producer',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Поставщик'),
        ),
    ]
