# Generated by Django 4.1.3 on 2022-11-21 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producer', '0004_alter_discountproducer_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producer',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
    ]
