# Generated by Django 4.1.4 on 2022-12-27 11:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('producer', '0005_alter_producer_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actionproducer',
            options={'verbose_name': "Producer's action", 'verbose_name_plural': "Producer's actions"},
        ),
        migrations.AlterModelOptions(
            name='discountproducer',
            options={'verbose_name': "Producer's customer discount", 'verbose_name_plural': "Producer's customer discounts"},
        ),
        migrations.AlterModelOptions(
            name='producer',
            options={'ordering': ['name'], 'verbose_name': 'Producer', 'verbose_name_plural': 'Producers'},
        ),
        migrations.AddField(
            model_name='producer',
            name='owner',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='actionproducer',
            name='amount_action',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='actionproducer',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='actionproducer',
            name='date_finish',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='actionproducer',
            name='date_start',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='actionproducer',
            name='description',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='actionproducer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='actionproducer',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='actionproducer',
            name='producers',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producer.producer'),
        ),
        migrations.AlterField(
            model_name='actionproducer',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='discountproducer',
            name='amount_discount',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='discountproducer',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='discountproducer',
            name='description',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='discountproducer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='discountproducer',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='discountproducer',
            name='producers',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producer.producer'),
        ),
        migrations.AlterField(
            model_name='discountproducer',
            name='quantity_cars_max',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="Max car's quantity for discount"),
        ),
        migrations.AlterField(
            model_name='discountproducer',
            name='quantity_cars_min',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="Min car's quantity for discount"),
        ),
        migrations.AlterField(
            model_name='discountproducer',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='producer',
            name='amount_of_clients',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='producer',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='producer',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
        migrations.AlterField(
            model_name='producer',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='producer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='producer',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='producer',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='producer',
            name='year_foundation',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
