# Generated by Django 4.1.2 on 2022-10-07 12:52

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('producer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoShow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название автосалона')),
                ('country', django_countries.fields.CountryField(max_length=2, verbose_name='Страна')),
                ('year_foundation', models.PositiveIntegerField(blank=True, verbose_name='Год основания')),
                ('balance', models.IntegerField(default=0, verbose_name='Баланс автосалона, USD')),
                ('wish_cars', models.CharField(blank=True, max_length=1500, verbose_name='Автомобили к приобретению')),
                ('list_auto', models.CharField(blank=True, max_length=1500, verbose_name='Список автомобилей салона')),
                ('list_producers', models.CharField(blank=True, max_length=1500, verbose_name='Список поставщиков')),
                ('list_customers', models.CharField(blank=True, max_length=1500, verbose_name='Список покупателей')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('action_producers', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='producer.actionproducer', verbose_name='Акция поставщика')),
                ('discount_producers', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='producer.discountproducer', verbose_name='Скидка поставщика')),
            ],
            options={
                'verbose_name': 'Автосалон',
                'verbose_name_plural': 'Автосалоны',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DiscountAutoShow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя скидки')),
                ('amount_discount', models.PositiveIntegerField(verbose_name='Размер скидки в %')),
                ('max_amount_spent', models.PositiveIntegerField(blank=True, null=True, verbose_name='Max сумма всех покупок для применения скидки')),
                ('min_amount_spent', models.PositiveIntegerField(blank=True, null=True, verbose_name='Min сумма всех покупок для применения скидки')),
                ('description', models.TextField(blank=True, max_length=500)),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('auto_shows', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto_show.autoshow', verbose_name='Автосалон')),
            ],
            options={
                'verbose_name': 'Скидка автосалона',
                'verbose_name_plural': 'Скидки автосалона',
            },
        ),
        migrations.CreateModel(
            name='ActionAutoShow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя акции')),
                ('amount_action', models.PositiveIntegerField(verbose_name='Размер скидки по акции в %')),
                ('date_start', models.DateTimeField(verbose_name='Дата начала акции (dd.mm.yyyy 00:00:00)')),
                ('date_finish', models.DateTimeField(verbose_name='Дата окончания акции (dd.mm.yyyy 00:00:00)')),
                ('description', models.TextField(blank=True, max_length=500)),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('auto_shows', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto_show.autoshow', verbose_name='Автосалон')),
            ],
            options={
                'verbose_name': 'Акция автосалона',
                'verbose_name_plural': 'Акции автосалона',
            },
        ),
    ]
