# Generated by Django 4.1.2 on 2022-10-07 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producer', '0001_initial'),
        ('auto_show', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autoshow',
            name='action_producers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='producer.actionproducer', verbose_name='Акция поставщика'),
        ),
        migrations.AlterField(
            model_name='autoshow',
            name='discount_producers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='producer.discountproducer', verbose_name='Скидка поставщика'),
        ),
    ]
