# Generated by Django 4.1.2 on 2022-10-10 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_show', '0002_alter_autoshow_action_producers_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discountautoshow',
            options={'verbose_name': 'Скидка постоянного клиента автосалона', 'verbose_name_plural': 'Скидки постоянного клиента автосалона'},
        ),
        migrations.AlterField(
            model_name='actionautoshow',
            name='amount_action',
            field=models.PositiveIntegerField(verbose_name='Скидка в %'),
        ),
        migrations.AlterField(
            model_name='actionautoshow',
            name='date_finish',
            field=models.DateTimeField(verbose_name='Дата окончания акции'),
        ),
        migrations.AlterField(
            model_name='actionautoshow',
            name='date_start',
            field=models.DateTimeField(verbose_name='Дата начала акции'),
        ),
        migrations.AlterField(
            model_name='actionautoshow',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='autoshow',
            name='list_auto',
            field=models.CharField(blank=True, max_length=1500, verbose_name='Список авто салона'),
        ),
        migrations.AlterField(
            model_name='autoshow',
            name='wish_cars',
            field=models.CharField(blank=True, max_length=1500, verbose_name='Авто к приобретению'),
        ),
        migrations.AlterField(
            model_name='discountautoshow',
            name='max_amount_spent',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Max сумма покупок для скидки'),
        ),
        migrations.AlterField(
            model_name='discountautoshow',
            name='min_amount_spent',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Min сумма покупок для скидки'),
        ),
        migrations.AlterField(
            model_name='discountautoshow',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
    ]
