# Generated by Django 4.1.2 on 2022-10-10 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_show', '0003_alter_discountautoshow_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autoshow',
            name='list_auto',
            field=models.CharField(blank=True, max_length=1500, null=True, verbose_name='Список авто салона'),
        ),
        migrations.AlterField(
            model_name='autoshow',
            name='list_customers',
            field=models.CharField(blank=True, max_length=1500, null=True, verbose_name='Список покупателей'),
        ),
        migrations.AlterField(
            model_name='autoshow',
            name='list_producers',
            field=models.CharField(blank=True, max_length=1500, null=True, verbose_name='Список поставщиков'),
        ),
        migrations.AlterField(
            model_name='autoshow',
            name='wish_cars',
            field=models.CharField(blank=True, max_length=1500, null=True, verbose_name='Авто к приобретению'),
        ),
        migrations.AlterField(
            model_name='autoshow',
            name='year_foundation',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Год основания'),
        ),
    ]
