# Generated by Django 4.1.3 on 2022-11-21 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_show', '0004_alter_autoshow_list_auto_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autoshow',
            options={'verbose_name': 'Автосалон', 'verbose_name_plural': 'Автосалоны'},
        ),
        migrations.RemoveField(
            model_name='autoshow',
            name='action_producers',
        ),
        migrations.RemoveField(
            model_name='autoshow',
            name='discount_producers',
        ),
        migrations.RemoveField(
            model_name='autoshow',
            name='wish_cars',
        ),
        migrations.AddField(
            model_name='autoshow',
            name='wish_car',
            field=models.TextField(blank=True, default='{"brand": None, "model": None, "year": None, "color": None, "price": None}', null=True),
        ),
        migrations.AlterField(
            model_name='autoshow',
            name='balance',
            field=models.IntegerField(default=0, verbose_name='Баланс, USD'),
        ),
        migrations.AlterField(
            model_name='autoshow',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
    ]
