version: '2.4'
services:
  web:
    build: .
    command: python /project/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/project
    ports:
      - 8000:8000
    depends_on:
      - db
      - redis
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres

    volumes:
      - postgres_data:/var/lib/postgresql/data/

  redis:
    image: redis

  celery:
    build: .
    command: celery -A my_showroom worker -l info
    volumes:
       - .:/project
    environment:
      - DEBUG=1
      - SECRET_KEY=django-insecure-ujrhdvphsx0%t7zzrq9pjaedp%^%z$x!rmaf2d2nw=ws9hyb=e
    depends_on:
      - redis
  celery-beat:
    build: .
    command: celery -A my_showroom beat -l info
    volumes:
      - .:/project
    environment:
      - DEBUG=1
      - SECRET_KEY=django-insecure-ujrhdvphsx0%t7zzrq9pjaedp%^%z$x!rmaf2d2nw=ws9hyb=e
    depends_on:
      - redis

volumes:
  postgres_data: