# Generated by Django 4.1.2 on 2022-10-07 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auto_show', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200, verbose_name='Имя покупателя')),
                ('last_name', models.CharField(max_length=200, verbose_name='Фамилия покупателя')),
                ('year_of_birth', models.PositiveIntegerField(blank=True, verbose_name='Год рождения')),
                ('balance', models.IntegerField(default=0, verbose_name='Баланс покупателя, USD')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('discount_auto_shows', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='auto_show.discountautoshow', verbose_name='Скидка автосалона')),
            ],
            options={
                'verbose_name': 'ФИ покупателя',
                'verbose_name_plural': 'ФИ покупателей',
            },
        ),
    ]
