# Generated by Django 4.1.2 on 2022-10-07 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auto_show', '0002_alter_autoshow_action_producers_and_more'),
        ('customer', '0002_alter_customer_year_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='discount_auto_shows',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auto_show.discountautoshow', verbose_name='Скидка автосалона'),
        ),
    ]
