# Generated by Django 4.1.3 on 2022-11-21 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_alter_customer_options_alter_customer_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='wish_car',
            field=models.TextField(blank=True, default='{"brand": None, "model": None, "year": None, "color": None, "price": None}', null=True),
        ),
    ]
