# Generated by Django 4.1.4 on 2022-12-27 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auto_show', '0007_alter_actionautoshow_options_alter_autoshow_options_and_more'),
        ('car', '0005_alter_car_options_alter_carinstance_options_and_more'),
        ('customer', '0007_alter_customer_options_customer_owner_and_more'),
        ('producer', '0006_alter_actionproducer_options_and_more'),
        ('deals', '0002_alter_deal_created_alter_deal_participants_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deal',
            options={'ordering': ['name'], 'verbose_name': 'Deal', 'verbose_name_plural': 'Deals'},
        ),
        migrations.AlterField(
            model_name='deal',
            name='auto_shows',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auto_show.autoshow'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='car_instances',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.carinstance'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='deal',
            name='customers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.customer'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='deal',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='deal',
            name='participants',
            field=models.CharField(choices=[('Producer-AutoShow', 'PRODUCER_AUTOSHOW'), ('AutoShow-Customer', 'AUTOSHOW_CUSTOMER')], max_length=50),
        ),
        migrations.AlterField(
            model_name='deal',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='deal',
            name='producers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='producer.producer'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
