# Generated by Django 4.1.2 on 2022-10-07 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auto_show', '0001_initial'),
        ('customer', '0001_initial'),
        ('producer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50, verbose_name='Бренд автомобиля')),
                ('model', models.CharField(max_length=50, verbose_name=' Mодель автомобиля')),
                ('year', models.CharField(max_length=4, verbose_name='Год автомобиля')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Автомобиль',
                'verbose_name_plural': 'Автомобили',
            },
        ),
        migrations.CreateModel(
            name='CarInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(blank=True, max_length=200, null=True, verbose_name='Цвет автомобиля')),
                ('price', models.PositiveIntegerField(verbose_name='Цена, USD')),
                ('condition', models.CharField(choices=[('wish_auto_show', 'желаемый для автосалона'), ('wish_customer', 'желаемый для покупателя'), ('in_showroom', 'в автосалоне'), ('at_producer', 'у поставщика'), ('at_customer', 'у покупателя')], max_length=40, verbose_name='Статус авто')),
                ('price_discount_auto_shows', models.PositiveIntegerField(blank=True, null=True, verbose_name='Цена со скидкой ПП, сделка автосалон-покупатель, USD')),
                ('price_discount_producers', models.PositiveIntegerField(blank=True, null=True, verbose_name='Цена со скидкой ПП, сделка поставщик-автосалон, USD')),
                ('price_action_auto_shows', models.PositiveIntegerField(blank=True, null=True, verbose_name='Цена по акции автосалона, USD')),
                ('price_action_producers', models.PositiveIntegerField(blank=True, null=True, verbose_name='Цена по акции поставщика, USD')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('action_auto_shows', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='auto_show.actionautoshow', verbose_name='Акция автосалона')),
                ('action_producers', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='producer.actionproducer', verbose_name='Акция поставщика')),
                ('auto_shows', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auto_show.autoshow', verbose_name='Автосалон')),
                ('customers', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.customer', verbose_name='Покупатель')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.car', verbose_name='Автомобиль')),
                ('producers', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='producer.producer', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Экземпляр автомобиля',
                'verbose_name_plural': 'Экземпляры автомобиля',
                'ordering': ['name'],
            },
        ),
    ]
