# Generated by Django 4.1.2 on 2022-10-10 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_alter_carinstance_action_auto_shows_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.CharField(max_length=50, verbose_name='Бренд'),
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.CharField(max_length=50, verbose_name=' Mодель'),
        ),
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.CharField(max_length=4, verbose_name='Год выпуска'),
        ),
        migrations.AlterField(
            model_name='carinstance',
            name='color',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Цвет'),
        ),
    ]
