# Generated by Django 4.1.3 on 2022-11-21 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_customer_wish_car'),
        ('auto_show', '0005_alter_autoshow_options_and_more'),
        ('producer', '0005_alter_producer_name'),
        ('car', '0003_alter_car_brand_alter_car_model_alter_car_year_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carinstance',
            name='action_auto_shows',
        ),
        migrations.RemoveField(
            model_name='carinstance',
            name='action_producers',
        ),
        migrations.RemoveField(
            model_name='carinstance',
            name='price_action_auto_shows',
        ),
        migrations.RemoveField(
            model_name='carinstance',
            name='price_action_producers',
        ),
        migrations.RemoveField(
            model_name='carinstance',
            name='price_discount_auto_shows',
        ),
        migrations.RemoveField(
            model_name='carinstance',
            name='price_discount_producers',
        ),
        migrations.AlterField(
            model_name='carinstance',
            name='auto_shows',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auto_shows', to='auto_show.autoshow', verbose_name='Автосалон'),
        ),
        migrations.AlterField(
            model_name='carinstance',
            name='condition',
            field=models.CharField(choices=[('Желаемый для автосалона', 'WISH_AUTO_SHOW'), ('Желаемый для покупателя', 'WISH_CUSTOMER'), ('В автосалоне', 'AT_AUTO_SHOW'), ('У поставщика', 'AT_PRODUCER'), ('У покупателя', 'AT_CUSTOMER')], max_length=60, verbose_name='Статус авто'),
        ),
        migrations.AlterField(
            model_name='carinstance',
            name='customers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='customer.customer', verbose_name='Покупатель'),
        ),
        migrations.AlterField(
            model_name='carinstance',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_instances', to='car.car', verbose_name='Автомобиль'),
        ),
        migrations.AlterField(
            model_name='carinstance',
            name='producers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='producers', to='producer.producer', verbose_name='Поставщик'),
        ),
    ]
