# Generated by Django 4.1.4 on 2022-12-28 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_auto_show',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_customer',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_producer',
        ),
        migrations.AddField(
            model_name='user',
            name='usertype',
            field=models.CharField(blank=True, choices=[('Is_AutoShow', 'Is_AutoShow'), ('Is_Customer', 'Is_Customer'), ('Is_Producer', 'Is_Producer')], default=None, max_length=50, null=True),
        ),
    ]
